on:
  push:
    branches:
      - master

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: rust
          package-name: bio-types
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"deps","section":"Dependencies","hidden":false}]'

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1.3.0
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish crate
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CRATES_IO_TOKEN }}
